# Generated by Django 2.2.6 on 2019-11-19 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserVk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ids', models.CharField(max_length=100, verbose_name='ID пользователя')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилие')),
                ('photo', models.CharField(max_length=100, verbose_name='Ссылка на фото')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdresesUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=255, verbose_name='Адресс доставки пользователя')),
                ('vk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk_info.UserVk')),
            ],
        ),
    ]
