# Generated by Django 2.2.6 on 2019-11-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_info', '0003_adresesuser_formadres'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresesuser',
            name='latitude',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='adresesuser',
            name='longitude',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Долгота'),
        ),
    ]
