# Generated by Django 2.2.6 on 2019-11-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vk_info', '0004_auto_20191120_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adresesuser',
            options={'verbose_name': 'Адрес пользователя Вк', 'verbose_name_plural': 'Адреса пользователей Вк'},
        ),
        migrations.AlterModelOptions(
            name='uservk',
            options={'verbose_name': 'Пользователь Вк', 'verbose_name_plural': 'Пользователи Вк'},
        ),
    ]
