# Generated by Django 2.2.6 on 2019-10-27 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191027_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='shop.Shop'),
        ),
        migrations.AddField(
            model_name='cart',
            name='vk_id',
            field=models.CharField(max_length=21, null=True, verbose_name='Вк айди'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='shop.CartItem'),
        ),
    ]
