# Generated by Django 2.2.6 on 2019-11-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Продукт корзины', 'verbose_name_plural': 'Продукты корзины'},
        ),
        migrations.AlterModelOptions(
            name='product_images',
            options={'verbose_name': 'Изабражение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AddField(
            model_name='product_images',
            name='file_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Путь к файлу'),
        ),
    ]
