# Generated by Django 2.2.6 on 2019-11-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20191116_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product_images',
            name='file_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='image_link',
            field=models.CharField(max_length=200, verbose_name='Ссылка на картинку Вконтакте'),
        ),
    ]
