# Generated by Django 2.2.6 on 2019-11-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk_info', '0004_auto_20191120_1449'),
        ('shop', '0007_auto_20191117_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('Предзаказ', 'Предзаказ'), ('Принят', 'Принят'), ('Отправлен', 'Отправлен'), ('Оплачен', 'Оплачен')], max_length=25, verbose_name='Статус заказа')),
                ('delivery', models.CharField(choices=[('Доставка', 'Доставка'), ('Самовывоз', 'Самовывоз')], max_length=25, verbose_name='Способ доставки')),
                ('adres', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон')),
                ('total_summ', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма')),
                ('products', models.CharField(max_length=255, verbose_name='Товары')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.Shop', verbose_name='Магазин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='vk_info.UserVk', verbose_name='Покупатель')),
            ],
        ),
    ]
